### ISSUE TITLE
Prepare S4 presentation (ROCC) for March 12

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/research-benchmarking-technology#14]
From Solly:

A few reminders as you prepare your material:
- You have 25 minutes to present, but as you know we're quite an interactive group. It's probably best to prepare 15-20 minutes worth of material, and expect plenty of questions and discussion.
- We have a wide range of backgrounds at Sage, so please make an effort to make as much of your materials as possible accessible to all. This means providing plenty of motivation and background material, as well as taking extra time to explain plots and results, as appropriate.
- Very little of our work happens in isolation. Please be sure to acknowledge others (especially internally) who have contributed to the work you present.

In order to send the seminar announcement, I'll need a talk title and your brief speaker bio. I currently have your titles as

    Verena Chung and Thomas Schaffter: Registry of Open Community Competitions (ROCC) 
    Sonia Carlson: Biomimicry: Innovating with nature’s genius

Please get me any changes to those, as well as your speaker bios by Wednesday. Be sure to include at least one fun fact about yourself for use in your intro.

## Tasks

- Submit speaker bio to Solly by Wednesday
  - [x] Verena
  - [ ] Thomas?
- [x] Prepare presentation

**Comment by vpchung** [comment]
[Current draft](https://docs.google.com/presentation/d/1DPt9jajqAJTIhBzbhNBub1Evw_5jdftPifGJ2NhTcFg/edit?usp=sharing) for the presentation

Definitely needs a review!

**Comment by tschaffter** [comment]
The above link redirects to the final presentation.
