### ISSUE TITLE
Add LB in front of ROCC EC2 + Route 53 record

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/research-benchmarking-technology#20]

**Comment by tschaffter** [comment]
@vpchung I can't find the ROCC EC2 on AWS. Can you point me to it?

Also if the EC2 is not in the region us-east-1, we would need to move it there to comply with an upcoming change to Sage policy of centralizing the resources in us-east-1.

**Comment by vpchung** [comment]
Currently, the instance is created via the AWS Service Catalog, and luckily, the region is us-east-1.  Per our discussion off GH, I'll look into whether we can instantiate a load balancer and DNS record / Route 53 via the service catalog.

**Comment by thomasyu888** [comment]
@vpchung , I don't think you can do that with the service catalog. You'll have to set up a github repo containing the infrastructure like [this](https://github.com/nlpsandbox/aws-cloudformation)

**Comment by tschaffter** [comment]
Meanwhile I will create the required resources tomorrow in the AWS sandbox environment (EC2, LB, R53 record)

**Comment by tschaffter** [comment]
Done. Here are the resources created:

- 1 EC2 (rocc)
- 1 Target Group (rocc)
- 2 Security Groups (rocc-http and rocc-https)
- 1 App Load Balancer (rocc-alb)
- 1 SSL certificate (*.rocc.sagesandbox.org)
- 1 DNS record (dev.rocc.sagesandbox.org)
