### ISSUE TITLE
ROCC July Dependencies Update

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/research-benchmarking-technology#39]
#### Repositories

- [x] Sage-Bionetworks/rocc-app
- [x] Sage-Bionetworks/rocc-schemas
- [x] Sage-Bionetworks/rocc-service
- [x] Sage-Bionetworks/rocc-client-angular

**Comment by vpchung** [comment]
Still waiting on the updates for rocc-app, but otherwise, done!

**Comment by tschaffter** [comment]
@vpchung I fixed the target branch of the dependabot config of rocc-app. PRs are now being opened in that repository.

**Comment by tschaffter** [comment]
@jiaxinmachine88 The update of the ROCC dependencies for July is now complete.
