### ISSUE TITLE
Document existing tool schemas and sources of data

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/research-benchmarking-technology#44]
Here are sources that I have identified through discussions with James, Robert, and Julie.

- [NFTI Data Model (Lucid)](https://lucid.app/lucidchart/3a118e5e-8884-48d1-af91-f03987bb0df8/edit?shared=true&page=pu72__N3nK2O&invitationId=inv_728349e4-c105-40e4-8a7f-3e0db9883a8a#)
- [nf_research_tools.rdb.model.csv](https://docs.google.com/spreadsheets/d/15fwIhZw7YfhPkzOfQhj6zU_5-_7ywS05-L8qOjMIVdM/edit#gid=0)
- https://cancercomplexity.synapse.org/Explore/Tools
- https://github.com/Sage-Bionetworks/csbc-pson-data-portal
- [CSBC/PSON RFC Presentation - Tool Metadata (slides)](https://docs.google.com/presentation/d/1Vez0xoQBo39OcPS3UrlwnClIZZCOaRsqB5ONnAqcsEA/edit#slide=id.g4d21a8c2ba_0_11)
- [CSBC/PS-ON: RFC Tools](https://docs.google.com/document/d/1FHayMenWJ1w_p9t5oFQv47HFscOb8I4Jf8kajB2yUTM/edit#heading=h.dv1uq7tt9axr)
- Slack chanel `#csbc` in Sage workspace
- https://ga4gh.github.io/tool-registry-service-schemas/
- https://github.com/bio-tools/biotoolsSchema
- https://bio.tools/
- https://www.synapse.org/#!Synapse:syn7080714/wiki/470471

## Task

- Organize these resources
- Contact our collaborators (mainly Dave and Chunlei) for additional resources that we should track.

**Comment by tschaffter** [comment]
@jiaxinmachine88 Schema-related resources shared this morning that we should track:

- https://discovery.biothings.io/view/outbreak#C
- https://github.com/outbreak-info/outbreak.info-resources/tree/master/yaml

**Comment by jiaxinmachine88** [comment]
Hiya - aggregated the above with the additional sources mentioned so far by collaborators (outbreak.info, ctsa search). 

I tried to separate out documentation, data, and schemas. Mind taking a look at the work so far and providing feedback? 

[RDP Schema Resources](https://docs.google.com/spreadsheets/d/1OFu2X0eGsKBFsZOLbVwgK6vjS0qbpjyDpa2mKMYxP4Q/edit#gid=287529991)

**Comment by tschaffter** [comment]
@jiaxinmachine88 Looks good!

**Comment by tschaffter** [comment]
@jiaxinmachine88 I have added resources to this spreadsheet (slides and shared folder).
