### ISSUE TITLE
Organize Lucid document for RBT and Projects

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/research-benchmarking-technology#49]
- [Research and Benchmarking Technology team folder](https://lucid.app/documents#/documents?folder_id=272649636)
- [Challenge Registry](https://lucid.app/documents#/documents?folder_id=272649616)

**Comment by tschaffter** [comment]
## Challenge Registry

Please add Lucidchart documents you have created to this [team folder](https://lucid.app/documents#/documents?folder_id=272649616&browser=icon).

- [ ] @jiaxinmachine88 
- [x] @vpchung 
- [x] @rrchai

**Comment by tschaffter** [comment]
@vpchung @jiaxinmachine88 Do you have Lucidchart documents that should be added to the newly created Challenge Registry shared folder on Lucidchart?

**Comment by vpchung** [comment]
@tschaffter I did not make any LucidCharts for the ROCC.
