### ISSUE TITLE
Create python-flask openapi generator template so that controllers aren't overwritten

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/research-benchmarking-technology#6]
Currently, there is quite a bit of work in having to undo the changes that the openapi-generator does, but if we created our own templates to import from a `core` module within the package that is unchanged, then it wouldn't be an issue.

Essentially this is the command I run to generate a service:
```
openapi-generator generate -i openapi.yaml -g python-flask -o server -t .codegen/server/
```

To get to this point, you will want to:

1. Create your own templates
   ```
   openapi-generator author template -g python-flask -o .codegen/server
   ```
2. Edit the templates in these two places:
    - [add import](https://github.com/Sage-Bionetworks/submission_service/blob/main/.codegen/server/controller.mustache#L7)
    - [update return](https://github.com/Sage-Bionetworks/submission_service/blob/main/.codegen/server/controller.mustache#L111-L114)
3. Create core module by copying everything in controllers in your packages into core.  [example](https://github.com/Sage-Bionetworks/submission_service/blob/main/server/openapi_server/core/controllers/queue_controller.py)
4. Run the generation command above and get something like this: [example](https://github.com/Sage-Bionetworks/submission_service/blob/main/server/openapi_server/controllers/queue_controller.py#L10-L30).  Notice how everything in controllers now just pulls from `core.controllers.queue_controller`?

**Comment by tschaffter** [comment]
We should create a GH repository where can be develop these template and either publish our custom `openapi-generator` to npmjs and/or Docker Hub (see [openapi-generator Dockerfile](https://github.com/OpenAPITools/openapi-generator/blob/master/Dockerfile)).

**Comment by tschaffter** [comment]
See https://github.com/nlpsandbox/date-annotator-example/pull/96#issuecomment-802553660
